import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    headerContainer: {
      backgroundColor: "#fff",
      // opacity: .90,
    },
    headerTitle: {
      color: "#2E5DB5",
      fontSize: 22,
      fontWeight: "500",
      paddingVertical: 6,
      textAlign: "center",
      shadowOffset: {
        height: 0.5,
        width: 0.5,
      },
      shadowOpacity: 0.2,
      shadowRadius: 5,
    },
    BoosterPassesContainerScroll: {
      // flex: 5,
      // // flexDirection: "column",
      // marginTop: 8,
      // marginHorizontal: 20,
      // backgroundColor: "black",
    },
    BoosterPassesContainer: {
      flex: 1,
      minHeight: 460,
      flexDirection: "column",
      // flexWrap: "wrap",
      marginTop: 8,
      marginHorizontal: 20,
      // backgroundColor: "black",
    },
  
    // BoosterPassesContainerModal: {
    //   flex: 1,
    //   flexDirection: "column",
    //   // flexWrap: "wrap",
    //   marginTop: 8,
    //   marginHorizontal: 20,
    // },
  
    BoosterPassContainer: {
      backgroundColor: "white",
      borderRadius: 20,
      opacity: 1,
      // borderBottomRightRadius: 20,
      // borderBottomLeftRadius: 20,
      elevation: 4,
      height: 370,
      flexDirection: "row",
      flexWrap: "wrap",
      marginBottom: -336,
  
      marginHorizontal: 12,
      marginVertical: 8,
      justifyContent: "center",
      shadowOffset: {
        height: 1,
        width: 1,
      },
      shadowOpacity: 1,
      shadowRadius: 10,
      shadowColor: "gray",
    },
    BoosterPassContainerModal: {
      backgroundColor: "white",
      borderRadius: 20,
      opacity: 1,
      // borderBottomRightRadius: 20,
      // borderBottomLeftRadius: 20,
      elevation: 4,
      height: 370,
      flexDirection: "row",
      flexWrap: "wrap",
      marginHorizontal: 12,
      marginVertical: 8,
      justifyContent: "center",
      shadowOffset: {
        height: 1,
        width: 1,
      },
      shadowOpacity: 1,
      shadowRadius: 10,
      shadowColor: "gray",
    },
    BoosterPassContainerModalUnselected: {
      backgroundColor: "white",
      borderRadius: 20,
      // borderBottomRightRadius: 20,
      // borderBottomLeftRadius: 20,
      // opacity: 0.4,
      elevation: 4,
      height: 370,
      flexDirection: "row",
      flexWrap: "wrap",
      marginHorizontal: 12,
      marginVertical: 8,
      justifyContent: "center",
      shadowOffset: {
        height: 1,
        width: 1,
      },
      shadowOpacity: 1,
      shadowRadius: 10,
      shadowColor: "gray",
    },
    backgroundimage: {
      width: "100%",
      height: "100%",
      borderRadius: 50,
    },
    // backgroundimageredeemed: {
    //   width: "100%",
    //   height: "100%",
    //   borderRadius: 50,
    // },
    BoosterPassHeader: {
      flexDirection: "column",
      padding: 0,
      marginTop: 10,
      marginBottom: 14,
      // shadowOffset: {
      //   height: 1,
      //   width: 1,
      // },
      // shadowOpacity: 0.2,
      // shadowRadius: 1,
    },
    BoosterPassHeaderRedeemed: {
      flexDirection: "column",
      padding: 0,
      opacity: 0.3,
      marginTop: 10,
      marginBottom: 14,
  
      // shadowOffset: {
      //   height: 1,
      //   width: 1,
      // },
      // shadowOpacity: 0.2,
      // shadowRadius: 1,
    },
    BoosterPassHeaderText1: {
      fontSize: 25,
      fontWeight: "500",
      textAlign: "center",
      shadowOffset: {
        height: 0.5,
        width: 0.5,
      },
      shadowOpacity: 0.2,
      shadowRadius: 5,
    },
    BoosterPassHeaderText1Redeemed: {
      fontSize: 25,
      fontWeight: "500",
      textAlign: "center",
      opacity: 1.3,
      shadowOffset: {
        height: 0.5,
        width: 0.5,
      },
      shadowOpacity: 0.2,
      shadowRadius: 5,
    },
    BoosterPassHeaderText2: {
      fontSize: 18,
      fontWeight: "700",
      alignSelf: "center",
    },
    // CouponItemContainer: {
    //   // flex: 1,
    //   flexDirection: "row",
  
    //   borderTopColor: "black",
    //   borderTopWidth: 1,
    //   // flexDirection: 'column',
    //   // alignContent: 'center',
    //   // backgroundColor: "red",
    //   flex: 1,
    //   // flexDirection: 'row',
    //   // justifyContent: 'center',
    //   justifyContent: "space-between",
    // },
    // CouponItemContainerDescription: {
    //   flex: 4,
    //   margin: 15,
    //   // backgroundColor: "blue",
    // },
    // CouponItemContainerExpiration: {
    //   flex: 1,
    //   backgroundColor: "blue",
    //   margin: 5,
    //   justifyContent: "center",
    // },
    BoosterPassSLContainer: {
      flexDirection: "row",
      backgroundColor: "white",
      padding: 0,
      alignContent: "center",
    },
    BoosterPassSLContainerRedeemed: {
      flexDirection: "row",
      backgroundColor: "white",
      padding: 0,
      alignContent: "center",
      opacity: 0.3,
    },
    BoosterPassTextIconsContainer: {
      flexDirection: "column",
      backgroundColor: "white",
      marginLeft: 10,
      justifyContent: "center",
    },
    BoosterPassIconsContainer: {
      flexDirection: "row",
      backgroundColor: "white",
      padding: 0,
    },
    BoosterPassLogosContainerText: {
      fontSize: 20,
      fontWeight: "600",
      alignSelf: "center",
      color: "green",
    },
    BoosterPassLogo: {
      width: 80,
      height: 70,
    },
    BoosterPassSLContainerIcons: {
      marginHorizontal: 10,
      marginTop: 5,
      width: 30,
      height: 30,
    },
    BoosterPassFooterContainer: {
      flexDirection: "column",
      alignItems: "center",
      marginTop: 125,
      padding: 0,
    },
    BoosterPassFooterContainerRedeemed: {
      flexDirection: "column",
      alignItems: "center",
      marginTop: 125,
      padding: 0,
      opacity: 0.3,
    },
    BoosterPassFooterText: {
      fontSize: 20,
      fontWeight: "600",
    },
    BoosterPassFooterImage: {
      marginHorizontal: 10,
      marginTop: 5,
      width: 180,
      height: 90,
    },
    redeemText: {
      color: "#fff",
      fontWeight: "800",
      alignSelf: "center",
    },
    redeemContainer: {
      backgroundColor: "#2E5DB5",
      borderRadius: 50,
      width: 100,
      borderWidth: 2,
      borderColor: "#2E5DB5",
      paddingTop: 10,
      paddingBottom: 10,
      shadowOffset: {
        height: 1,
        width: 1,
      },
      shadowOpacity: 0.6,
      shadowRadius: 5,
    },
    PurchaseContainer: {
      flexDirection: "column",
      alignItems: "center",
      // marginTop: 125,
      padding: 0,
    },
    PurchaseButton: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 14,
      marginTop: -30,
      width: 190,
      borderRadius: 50,
      elevation: 3,
      backgroundColor: "#F2A842",
    },
    PurchaseText: {
      fontSize: 19,
      lineHeight: 21,
      fontWeight: "500",
      letterSpacing: 0.25,
      color: "white",
    },
  });

  export default styles;